# Site settings
title: D Welengoda
twitter_username: Welengoda.D
name: D Welengoda

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: https://https://freemovieswebsitesonline.blogspot.com/#!
 - title: GitHub
   url: https://github.com/d
 - title: LinkedIn
   url: https://www.linkedin.com/pub/dwelengoda
 - title: Food
   url: https://www.robbishfood.com/
 - title: Driving
   url: https://www.dmv.org/learning-drive.php

#Any buzzword skills you want to include
skills:
 - Running
 - Movie watching
 - Listening to music
 - Fast food
 - Socializing
 - Presentation
 
roles:
 - title: Executive
   start: 2007
   end: Ongoing
   employer: Sampath Bank PLC
   description: ATM Maintenance. 
 - title: Junior Engineer
   start: 2007
   end: 2014
   employer: PricewaterhouseCoopers
   description: Technology Consultancy
   - title: Consultant
   start: 2014
   end: To-Date

#Education is required
education:
 - level: Bachelor of Science (B.Sc.)
   date: 2007
   subject: Computer Networks and Data Communication
   school: Sri Lanka Institute of Information Technology

